### PR TITLE
Fix line break bug, aka 'Cannot read property 'color' of undefined' (#4)

### LINKED ISSUE #4: Cannot read property 'color' of undefined
The original issue comes from Gitea: https://github.com/go-gitea/gitea/issues/3382

But still I'm duplicating the text:

## Description

There're not so many branches that a currently simultaneously used (around 6-7), however the overall number of branches is 28. Something started to go wrong today then the git graph stopped to display correctly—there're no more colors at all. Below are the screenshots of the problem.

Unfortunately I really cannot give more info about the problem because our development process haven't changed for a long time: We just commit and push and very often review this git graph on out instance of Gitea. And out of the blue it gets white with an error in JS console.

My first assumption was that it may be connected with the fact than each new branch gets it own color, and maybe there's a finite number of colors to display, however 28 branches isn't a limit at all for a bit project... So I do believe the assumption is wrong.

## Screenshots

The result of something goes wrong with git graph:

image

What the developer tools in Chrome outputs regarding the error:

image

The direct place in the JS file where the error occurs:

image

### PR DESCRIPTION
**Pull request by axifive**
Hello. I did a little refactoring. And added fix #4

You can show this bug [here](https://axifive.github.io/fixgitgraph/)

And fix [here](https://rawgit.com/axifive/fixgitgraph/master/index.html)

### CODE REVIEW

File: gitgraph.js [hunk 1]
```diff
@@ -125,7 +125,20 @@ var gitGraph = function (canvas, rawGraphList, config) {
 			!(row[i - 2] && row[i] === "_" && row[i - 2] === "|")) {}
 		
 		return i;
-	}
+	};
+	
+	var findLineBreak = function (row) {
+		if (!row) {
```
Comment (lafriks) [inline gitgraph.js:131]: I think there should also need to have check ` || row.length === 0` just to be sure not to have infinite loop below in unexpected corner case

Comment (axifive) [reply gitgraph.js:131]: postfix decrement in the while loop returns `0` what's stops it, and `row.length` can't be negative
